updated pom and server.xml for 2.0 plugin
mattbsox/sample.javaee7.jta pull request #1
Opened 2017-05-17 20:34 UTC by mattbsox

2017-05-26 15:05 UTC, patricktiu requested changes

2017-05-26 15:05 UTC, patricktiu commented on pom.xml
> +                    <type>zip</type>
You can delete line 90 `<type>zip</zip>` which is only used within the `<install>` or `<assemblyArtifact>` element.

see https://github.com/WASdev/ci.maven/blob/master/docs/installation-configuration.md

2017-05-26 15:40 UTC, mattbsox commented on pom.xml
> +                    <type>zip</type>
Okay, I'll fix that in the rest of the samples too.

2017-05-26 19:54 UTC, patricktiu requested changes

2017-05-26 19:54 UTC, patricktiu commented on pom.xml
> +            <version>1.2-b03</version>
This is a problem in the original sample.  javax.transaction-api dependency should have `provided` scope.

2017-05-26 19:54 UTC, patricktiu commented on pom.xml
> +                                    <outputDirectory>${project.build.directory}/liberty/wlp/usr/shared/resource/derby</outputDirectory>
typo:

${project.build.directory}/liberty/wlp/usr/shared/`resources`/derby

2017-05-26 19:54 UTC, patricktiu commented on src/main/wlp/server.xml
> +        <file name="${wlp.user.dir}/shared/resource/derby/derby.jar"/>
change it back to 

`<file name="${shared.resource.dir}/derby/derby.jar"/>`

See KC for the value of ${shared.resource.dir}:
https://www.ibm.com/support/knowledgecenter/SS7K4U_liberty/com.ibm.websphere.wlp.nd.multiplatform.doc/ae/rwlp_dirs.html

2017-05-26 19:54 UTC, patricktiu commented on src/main/wlp/server.xml
> +        <properties.derby.embedded createDatabase="create" databaseName="${wlp.user.dir}/shared/resource/derby/JTASAMPLE"/>
change it back to 

`<properties.derby.embedded createDatabase="create" databaseName="${shared.resource.dir}/derby/JTASAMPLE"/>`

2017-05-30 17:18 UTC, patricktiu approved these changes

2017-06-06 01:54 UTC, patricktiu approved these changes

2017-06-06 15:19 UTC, merged